export interface FontOption {
  name: string;
  family: string;
  category: 'display' | 'sans' | 'serif' | 'mono' | 'handwritten' | 'decorative' | 'horror' | 'retro' | 'graffiti' | 'elegant' | 'futuristic' | 'vintage' | 'brush' | 'stencil' | 'outline' | 'rounded' | 'condensed' | 'slab' | 'geometric';
}

export const CURATED_FONTS: FontOption[] = [
  // =====================================================
  // DISPLAY - Bold, impactful headline fonts (100+ fonts)
  // =====================================================
  { name: 'Anton', family: "'Anton', sans-serif", category: 'display' },
  { name: 'Bebas Neue', family: "'Bebas Neue', sans-serif", category: 'display' },
  { name: 'Black Ops One', family: "'Black Ops One', system-ui", category: 'display' },
  { name: 'Bungee', family: "'Bungee', sans-serif", category: 'display' },
  { name: 'Bungee Inline', family: "'Bungee Inline', sans-serif", category: 'display' },
  { name: 'Bungee Outline', family: "'Bungee Outline', sans-serif", category: 'display' },
  { name: 'Bungee Shade', family: "'Bungee Shade', sans-serif", category: 'display' },
  { name: 'Fugaz One', family: "'Fugaz One', sans-serif", category: 'display' },
  { name: 'Lilita One', family: "'Lilita One', sans-serif", category: 'display' },
  { name: 'Righteous', family: "'Righteous', sans-serif", category: 'display' },
  { name: 'Russo One', family: "'Russo One', sans-serif", category: 'display' },
  { name: 'Staatliches', family: "'Staatliches', sans-serif", category: 'display' },
  { name: 'Archivo Black', family: "'Archivo Black', sans-serif", category: 'display' },
  { name: 'Alfa Slab One', family: "'Alfa Slab One', serif", category: 'display' },
  { name: 'Bowlby One SC', family: "'Bowlby One SC', sans-serif", category: 'display' },
  { name: 'Concert One', family: "'Concert One', sans-serif", category: 'display' },
  { name: 'Contrail One', family: "'Contrail One', sans-serif", category: 'display' },
  { name: 'Dela Gothic One', family: "'Dela Gothic One', sans-serif", category: 'display' },
  { name: 'Faster One', family: "'Faster One', sans-serif", category: 'display' },
  { name: 'Gravitas One', family: "'Gravitas One', serif", category: 'display' },
  { name: 'Passion One', family: "'Passion One', sans-serif", category: 'display' },
  { name: 'Patua One', family: "'Patua One', serif", category: 'display' },
  { name: 'Poller One', family: "'Poller One', serif", category: 'display' },
  { name: 'Racing Sans One', family: "'Racing Sans One', sans-serif", category: 'display' },
  { name: 'Rammetto One', family: "'Rammetto One', sans-serif", category: 'display' },
  { name: 'Sigmar One', family: "'Sigmar One', sans-serif", category: 'display' },
  { name: 'Titan One', family: "'Titan One', sans-serif", category: 'display' },
  { name: 'Viga', family: "'Viga', sans-serif", category: 'display' },
  { name: 'Fira Sans', family: "'Fira Sans', sans-serif", category: 'display' },
  { name: 'Oswald', family: "'Oswald', sans-serif", category: 'display' },
  { name: 'Gajraj One', family: "'Gajraj One', sans-serif", category: 'display' },
  { name: 'Rubik Distressed', family: "'Rubik Distressed', sans-serif", category: 'display' },
  { name: 'Rubik Burned', family: "'Rubik Burned', sans-serif", category: 'display' },
  { name: 'Rubik Maze', family: "'Rubik Maze', sans-serif", category: 'display' },
  { name: 'Rubik Doodle Shadow', family: "'Rubik Doodle Shadow', sans-serif", category: 'display' },
  { name: 'Rubik Iso', family: "'Rubik Iso', sans-serif", category: 'display' },
  { name: 'Rubik Lines', family: "'Rubik Lines', sans-serif", category: 'display' },
  { name: 'Rubik Scribble', family: "'Rubik Scribble', sans-serif", category: 'display' },
  { name: 'Rubik Storm', family: "'Rubik Storm', sans-serif", category: 'display' },
  { name: 'Rubik Broken Fax', family: "'Rubik Broken Fax', sans-serif", category: 'display' },
  { name: 'Rubik Dirt', family: "'Rubik Dirt', sans-serif", category: 'display' },
  { name: 'Teko', family: "'Teko', sans-serif", category: 'display' },
  { name: 'Changa', family: "'Changa', sans-serif", category: 'display' },
  { name: 'Bai Jamjuree', family: "'Bai Jamjuree', sans-serif", category: 'display' },
  { name: 'Chakra Petch', family: "'Chakra Petch', sans-serif", category: 'display' },
  { name: 'Heebo', family: "'Heebo', sans-serif", category: 'display' },
  { name: 'Kanit', family: "'Kanit', sans-serif", category: 'display' },
  { name: 'Prompt', family: "'Prompt', sans-serif", category: 'display' },
  { name: 'Sarabun', family: "'Sarabun', sans-serif", category: 'display' },
  { name: 'Exo 2', family: "'Exo 2', sans-serif", category: 'display' },
  { name: 'Barlow', family: "'Barlow', sans-serif", category: 'display' },
  { name: 'Barlow Condensed', family: "'Barlow Condensed', sans-serif", category: 'display' },
  { name: 'Barlow Semi Condensed', family: "'Barlow Semi Condensed', sans-serif", category: 'display' },
  { name: 'Big Shoulders Display', family: "'Big Shoulders Display', sans-serif", category: 'display' },
  { name: 'Big Shoulders Text', family: "'Big Shoulders Text', sans-serif", category: 'display' },
  { name: 'Big Shoulders Stencil Display', family: "'Big Shoulders Stencil Display', sans-serif", category: 'display' },
  { name: 'Big Shoulders Inline Display', family: "'Big Shoulders Inline Display', sans-serif", category: 'display' },
  { name: 'Saira', family: "'Saira', sans-serif", category: 'display' },
  { name: 'Saira Condensed', family: "'Saira Condensed', sans-serif", category: 'display' },
  { name: 'Saira Extra Condensed', family: "'Saira Extra Condensed', sans-serif", category: 'display' },
  { name: 'Saira Semi Condensed', family: "'Saira Semi Condensed', sans-serif", category: 'display' },
  { name: 'Quantico', family: "'Quantico', sans-serif", category: 'display' },
  { name: 'Play', family: "'Play', sans-serif", category: 'display' },
  { name: 'Arvo', family: "'Arvo', serif", category: 'display' },
  { name: 'Coda', family: "'Coda', sans-serif", category: 'display' },
  { name: 'Lalezar', family: "'Lalezar', sans-serif", category: 'display' },
  { name: 'Chango', family: "'Chango', sans-serif", category: 'display' },
  { name: 'Archivo Narrow', family: "'Archivo Narrow', sans-serif", category: 'display' },
  { name: 'Fjalla One', family: "'Fjalla One', sans-serif", category: 'display' },
  { name: 'Pathway Gothic One', family: "'Pathway Gothic One', sans-serif", category: 'display' },
  { name: 'Pathway Extreme', family: "'Pathway Extreme', sans-serif", category: 'display' },
  { name: 'Secular One', family: "'Secular One', sans-serif", category: 'display' },
  { name: 'Squada One', family: "'Squada One', sans-serif", category: 'display' },
  { name: 'Stint Ultra Condensed', family: "'Stint Ultra Condensed', serif", category: 'display' },
  { name: 'Stint Ultra Expanded', family: "'Stint Ultra Expanded', serif", category: 'display' },
  { name: 'Timmana', family: "'Timmana', sans-serif", category: 'display' },
  { name: 'Turret Road', family: "'Turret Road', sans-serif", category: 'display' },
  { name: 'Jockey One', family: "'Jockey One', sans-serif", category: 'display' },
  { name: 'Hammersmith One', family: "'Hammersmith One', sans-serif", category: 'display' },
  { name: 'Aldrich', family: "'Aldrich', sans-serif", category: 'display' },
  { name: 'Electrolize', family: "'Electrolize', sans-serif", category: 'display' },
  { name: 'Michroma', family: "'Michroma', sans-serif", category: 'display' },
  { name: 'Syncopate', family: "'Syncopate', sans-serif", category: 'display' },
  { name: 'Unica One', family: "'Unica One', sans-serif", category: 'display' },
  { name: 'Yeseva One', family: "'Yeseva One', serif", category: 'display' },
  { name: 'Aclonica', family: "'Aclonica', sans-serif", category: 'display' },
  { name: 'Allan', family: "'Allan', sans-serif", category: 'display' },
  { name: 'Allerta', family: "'Allerta', sans-serif", category: 'display' },
  { name: 'Allerta Stencil', family: "'Allerta Stencil', sans-serif", category: 'display' },
  { name: 'Almendra Display', family: "'Almendra Display', serif", category: 'display' },
  { name: 'Audiowide', family: "'Audiowide', sans-serif", category: 'display' },
  { name: 'Averia Gruesa Libre', family: "'Averia Gruesa Libre', cursive", category: 'display' },
  { name: 'Averia Libre', family: "'Averia Libre', cursive", category: 'display' },
  { name: 'Averia Sans Libre', family: "'Averia Sans Libre', cursive", category: 'display' },
  { name: 'Averia Serif Libre', family: "'Averia Serif Libre', cursive", category: 'display' },
  { name: 'Baloo 2', family: "'Baloo 2', cursive", category: 'display' },
  { name: 'Baloo Bhai 2', family: "'Baloo Bhai 2', cursive", category: 'display' },
  { name: 'Baloo Bhaijaan 2', family: "'Baloo Bhaijaan 2', cursive", category: 'display' },
  { name: 'Baloo Bhaina 2', family: "'Baloo Bhaina 2', cursive", category: 'display' },
  { name: 'Baloo Chettan 2', family: "'Baloo Chettan 2', cursive", category: 'display' },
  { name: 'Baloo Da 2', family: "'Baloo Da 2', cursive", category: 'display' },
  { name: 'Baloo Paaji 2', family: "'Baloo Paaji 2', cursive", category: 'display' },
  { name: 'Baloo Tamma 2', family: "'Baloo Tamma 2', cursive", category: 'display' },
  { name: 'Baloo Tammudu 2', family: "'Baloo Tammudu 2', cursive", category: 'display' },
  { name: 'Baloo Thambi 2', family: "'Baloo Thambi 2', cursive", category: 'display' },
  { name: 'Belleza', family: "'Belleza', sans-serif", category: 'display' },
  { name: 'BenchNine', family: "'BenchNine', sans-serif", category: 'display' },
  { name: 'Bree Serif', family: "'Bree Serif', serif", category: 'display' },
  { name: 'Candal', family: "'Candal', sans-serif", category: 'display' },
  { name: 'Capriola', family: "'Capriola', sans-serif", category: 'display' },
  { name: 'Carter One', family: "'Carter One', cursive", category: 'display' },
  { name: 'Coda Caption', family: "'Coda Caption', sans-serif", category: 'display' },
  { name: 'Days One', family: "'Days One', sans-serif", category: 'display' },
  { name: 'Denk One', family: "'Denk One', sans-serif", category: 'display' },

  // =====================================================
  // DECORATIVE - Unique, eye-catching styles (80+ fonts)
  // =====================================================
  { name: 'Monoton', family: "'Monoton', sans-serif", category: 'decorative' },
  { name: 'Fascinate', family: "'Fascinate', system-ui", category: 'decorative' },
  { name: 'Honk', family: "'Honk', system-ui", category: 'decorative' },
  { name: 'Codystar', family: "'Codystar', sans-serif", category: 'decorative' },
  { name: 'Emblema One', family: "'Emblema One', sans-serif", category: 'decorative' },
  { name: 'Ewert', family: "'Ewert', serif", category: 'decorative' },
  { name: 'Flamenco', family: "'Flamenco', sans-serif", category: 'decorative' },
  { name: 'Flavors', family: "'Flavors', sans-serif", category: 'decorative' },
  { name: 'Henny Penny', family: "'Henny Penny', cursive", category: 'decorative' },
  { name: 'Kavoon', family: "'Kavoon', serif", category: 'decorative' },
  { name: 'Keania One', family: "'Keania One', sans-serif", category: 'decorative' },
  { name: 'Kenia', family: "'Kenia', sans-serif", category: 'decorative' },
  { name: 'Lacquer', family: "'Lacquer', sans-serif", category: 'decorative' },
  { name: 'Lemon', family: "'Lemon', serif", category: 'decorative' },
  { name: 'Modak', family: "'Modak', sans-serif", category: 'decorative' },
  { name: 'Nabla', family: "'Nabla', sans-serif", category: 'decorative' },
  { name: 'Piedra', family: "'Piedra', serif", category: 'decorative' },
  { name: 'Plaster', family: "'Plaster', sans-serif", category: 'decorative' },
  { name: 'Revalia', family: "'Revalia', sans-serif", category: 'decorative' },
  { name: 'Rowdies', family: "'Rowdies', sans-serif", category: 'decorative' },
  { name: 'Shrikhand', family: "'Shrikhand', serif", category: 'decorative' },
  { name: 'Spicy Rice', family: "'Spicy Rice', sans-serif", category: 'decorative' },
  { name: 'Unlock', family: "'Unlock', sans-serif", category: 'decorative' },
  { name: 'Yatra One', family: "'Yatra One', sans-serif", category: 'decorative' },
  { name: 'ZCOOL KuaiLe', family: "'ZCOOL KuaiLe', sans-serif", category: 'decorative' },
  { name: 'ZCOOL QingKe HuangYou', family: "'ZCOOL QingKe HuangYou', sans-serif", category: 'decorative' },
  { name: 'Rye', family: "'Rye', serif", category: 'decorative' },
  { name: 'Bungee Spice', family: "'Bungee Spice', sans-serif", category: 'decorative' },
  { name: 'Foldit', family: "'Foldit', sans-serif", category: 'decorative' },
  { name: 'Climate Crisis', family: "'Climate Crisis', sans-serif", category: 'decorative' },
  { name: 'Blaka', family: "'Blaka', sans-serif", category: 'decorative' },
  { name: 'Blaka Hollow', family: "'Blaka Hollow', sans-serif", category: 'decorative' },
  { name: 'Blaka Ink', family: "'Blaka Ink', sans-serif", category: 'decorative' },
  { name: 'Atomic Age', family: "'Atomic Age', cursive", category: 'decorative' },
  { name: 'Baumans', family: "'Baumans', cursive", category: 'decorative' },
  { name: 'Bigelow Rules', family: "'Bigelow Rules', cursive", category: 'decorative' },
  { name: 'Butterfly Kids', family: "'Butterfly Kids', cursive", category: 'decorative' },
  { name: 'Fascinate Inline', family: "'Fascinate Inline', cursive", category: 'decorative' },
  { name: 'Finger Paint', family: "'Finger Paint', cursive", category: 'decorative' },
  { name: 'Freckle Face', family: "'Freckle Face', cursive", category: 'decorative' },
  { name: 'Frijole', family: "'Frijole', cursive", category: 'decorative' },
  { name: 'Gorditas', family: "'Gorditas', cursive", category: 'decorative' },
  { name: 'Jacques Francois Shadow', family: "'Jacques Francois Shadow', serif", category: 'decorative' },
  { name: 'Jolly Lodger', family: "'Jolly Lodger', cursive", category: 'decorative' },
  { name: 'Londrina Outline', family: "'Londrina Outline', cursive", category: 'decorative' },
  { name: 'Londrina Shadow', family: "'Londrina Shadow', cursive", category: 'decorative' },
  { name: 'Londrina Sketch', family: "'Londrina Sketch', cursive", category: 'decorative' },
  { name: 'Londrina Solid', family: "'Londrina Solid', cursive", category: 'decorative' },
  { name: 'Megrim', family: "'Megrim', cursive", category: 'decorative' },
  { name: 'Metal Mania', family: "'Metal Mania', cursive", category: 'decorative' },
  { name: 'Miltonian', family: "'Miltonian', cursive", category: 'decorative' },
  { name: 'Mystery Quest', family: "'Mystery Quest', cursive", category: 'decorative' },
  { name: 'Nova Cut', family: "'Nova Cut', cursive", category: 'decorative' },
  { name: 'Nova Flat', family: "'Nova Flat', cursive", category: 'decorative' },
  { name: 'Nova Mono', family: "'Nova Mono', monospace", category: 'decorative' },
  { name: 'Nova Oval', family: "'Nova Oval', cursive", category: 'decorative' },
  { name: 'Nova Round', family: "'Nova Round', cursive", category: 'decorative' },
  { name: 'Nova Script', family: "'Nova Script', cursive", category: 'decorative' },
  { name: 'Nova Slim', family: "'Nova Slim', cursive", category: 'decorative' },
  { name: 'Nova Square', family: "'Nova Square', cursive", category: 'decorative' },
  { name: 'Offside', family: "'Offside', cursive", category: 'decorative' },
  { name: 'Original Surfer', family: "'Original Surfer', cursive", category: 'decorative' },
  { name: 'Over the Rainbow', family: "'Over the Rainbow', cursive", category: 'decorative' },
  { name: 'Passero One', family: "'Passero One', cursive", category: 'decorative' },
  { name: 'Plaster', family: "'Plaster', cursive", category: 'decorative' },
  { name: 'Poiret One', family: "'Poiret One', cursive", category: 'decorative' },
  { name: 'Pompiere', family: "'Pompiere', cursive", category: 'decorative' },
  { name: 'Ranga', family: "'Ranga', cursive", category: 'decorative' },
  { name: 'Ravi Prakash', family: "'Ravi Prakash', cursive", category: 'decorative' },
  { name: 'Risque', family: "'Risque', cursive", category: 'decorative' },
  { name: 'Sahitya', family: "'Sahitya', serif", category: 'decorative' },
  { name: 'Sancreek', family: "'Sancreek', cursive", category: 'decorative' },
  { name: 'Sarina', family: "'Sarina', cursive", category: 'decorative' },
  { name: 'Seaweed Script', family: "'Seaweed Script', cursive", category: 'decorative' },
  { name: 'Sevillana', family: "'Sevillana', cursive", category: 'decorative' },
  { name: 'Shojumaru', family: "'Shojumaru', cursive", category: 'decorative' },
  { name: 'Smokum', family: "'Smokum', cursive", category: 'decorative' },
  { name: 'Snowburst One', family: "'Snowburst One', cursive", category: 'decorative' },
  { name: 'Srisakdi', family: "'Srisakdi', cursive", category: 'decorative' },
  { name: 'Stalinist One', family: "'Stalinist One', cursive", category: 'decorative' },
  { name: 'Stardos Stencil', family: "'Stardos Stencil', cursive", category: 'decorative' },

  // =====================================================
  // HORROR - Creepy, spooky fonts (25+ fonts)
  // =====================================================
  { name: 'Creepster', family: "'Creepster', system-ui", category: 'horror' },
  { name: 'Nosifer', family: "'Nosifer', system-ui", category: 'horror' },
  { name: 'Butcherman', family: "'Butcherman', cursive", category: 'horror' },
  { name: 'Eater', family: "'Eater', cursive", category: 'horror' },
  { name: 'Irish Grover', family: "'Irish Grover', cursive", category: 'horror' },
  { name: 'Miltonian Tattoo', family: "'Miltonian Tattoo', cursive", category: 'horror' },
  { name: 'New Rocker', family: "'New Rocker', cursive", category: 'horror' },
  { name: 'Pirata One', family: "'Pirata One', sans-serif", category: 'horror' },
  { name: 'Vampiro One', family: "'Vampiro One', cursive", category: 'horror' },
  { name: 'Underdog', family: "'Underdog', cursive", category: 'horror' },
  { name: 'UnifrakturCook', family: "'UnifrakturCook', cursive", category: 'horror' },
  { name: 'UnifrakturMaguntia', family: "'UnifrakturMaguntia', serif", category: 'horror' },
  { name: 'Almendra', family: "'Almendra', serif", category: 'horror' },
  { name: 'Almendra SC', family: "'Almendra SC', serif", category: 'horror' },
  { name: 'Griffy', family: "'Griffy', cursive", category: 'horror' },
  { name: 'Grenze', family: "'Grenze', serif", category: 'horror' },
  { name: 'Grenze Gotisch', family: "'Grenze Gotisch', serif", category: 'horror' },
  { name: 'IM Fell DW Pica', family: "'IM Fell DW Pica', serif", category: 'horror' },
  { name: 'IM Fell DW Pica SC', family: "'IM Fell DW Pica SC', serif", category: 'horror' },
  { name: 'IM Fell Double Pica', family: "'IM Fell Double Pica', serif", category: 'horror' },
  { name: 'IM Fell English', family: "'IM Fell English', serif", category: 'horror' },
  { name: 'IM Fell English SC', family: "'IM Fell English SC', serif", category: 'horror' },
  { name: 'IM Fell French Canon', family: "'IM Fell French Canon', serif", category: 'horror' },
  { name: 'IM Fell French Canon SC', family: "'IM Fell French Canon SC', serif", category: 'horror' },
  { name: 'IM Fell Great Primer', family: "'IM Fell Great Primer', serif", category: 'horror' },
  { name: 'IM Fell Great Primer SC', family: "'IM Fell Great Primer SC', serif", category: 'horror' },

  // =====================================================
  // RETRO/PIXEL - Gaming and tech vibes (40+ fonts)
  // =====================================================
  { name: 'Press Start 2P', family: "'Press Start 2P', monospace", category: 'retro' },
  { name: 'Silkscreen', family: "'Silkscreen', monospace", category: 'retro' },
  { name: 'VT323', family: "'VT323', monospace", category: 'retro' },
  { name: 'Orbitron', family: "'Orbitron', sans-serif", category: 'retro' },
  { name: 'Rubik Mono One', family: "'Rubik Mono One', monospace", category: 'retro' },
  { name: 'Major Mono Display', family: "'Major Mono Display', monospace", category: 'retro' },
  { name: 'Iceland', family: "'Iceland', sans-serif", category: 'retro' },
  { name: 'Wallpoet', family: "'Wallpoet', sans-serif", category: 'retro' },
  { name: 'Gugi', family: "'Gugi', sans-serif", category: 'retro' },
  { name: 'Saira Stencil One', family: "'Saira Stencil One', sans-serif", category: 'retro' },
  { name: 'Train One', family: "'Train One', sans-serif", category: 'retro' },
  { name: 'Rubik Pixels', family: "'Rubik Pixels', sans-serif", category: 'retro' },
  { name: 'Pixelify Sans', family: "'Pixelify Sans', sans-serif", category: 'retro' },
  { name: 'DotGothic16', family: "'DotGothic16', sans-serif", category: 'retro' },
  { name: 'Kode Mono', family: "'Kode Mono', monospace", category: 'retro' },
  { name: 'Share Tech', family: "'Share Tech', sans-serif", category: 'retro' },
  { name: 'Share Tech Mono', family: "'Share Tech Mono', monospace", category: 'retro' },
  { name: 'Xanh Mono', family: "'Xanh Mono', monospace", category: 'retro' },
  { name: 'B612 Mono', family: "'B612 Mono', monospace", category: 'retro' },
  { name: 'Courier Prime', family: "'Courier Prime', monospace", category: 'retro' },
  { name: 'Cutive Mono', family: "'Cutive Mono', monospace", category: 'retro' },
  { name: 'Inconsolata', family: "'Inconsolata', monospace", category: 'retro' },
  { name: 'Nanum Gothic Coding', family: "'Nanum Gothic Coding', monospace", category: 'retro' },
  { name: 'Overpass Mono', family: "'Overpass Mono', monospace", category: 'retro' },
  { name: 'PT Mono', family: "'PT Mono', monospace", category: 'retro' },
  { name: 'Roboto Mono', family: "'Roboto Mono', monospace", category: 'retro' },
  { name: 'Syne Mono', family: "'Syne Mono', monospace", category: 'retro' },
  { name: 'Syne Tactile', family: "'Syne Tactile', cursive", category: 'retro' },
  { name: 'Nova Mono', family: "'Nova Mono', monospace", category: 'retro' },
  { name: 'Azeret Mono', family: "'Azeret Mono', monospace", category: 'retro' },
  { name: 'Red Hat Mono', family: "'Red Hat Mono', monospace", category: 'retro' },
  { name: 'Noto Sans Mono', family: "'Noto Sans Mono', monospace", category: 'retro' },
  { name: 'IBM Plex Mono', family: "'IBM Plex Mono', monospace", category: 'retro' },
  { name: 'Fragment Mono', family: "'Fragment Mono', monospace", category: 'retro' },
  { name: 'Spline Sans Mono', family: "'Spline Sans Mono', monospace", category: 'retro' },
  { name: 'Martian Mono', family: "'Martian Mono', monospace", category: 'retro' },
  { name: 'Geist Mono', family: "'Geist Mono', monospace", category: 'retro' },

  // =====================================================
  // GRAFFITI/STREET - Urban, bold styles (35+ fonts)
  // =====================================================
  { name: 'Bangers', family: "'Bangers', cursive", category: 'graffiti' },
  { name: 'Boogaloo', family: "'Boogaloo', sans-serif", category: 'graffiti' },
  { name: 'Chewy', family: "'Chewy', sans-serif", category: 'graffiti' },
  { name: 'Knewave', family: "'Knewave', sans-serif", category: 'graffiti' },
  { name: 'Kranky', family: "'Kranky', sans-serif", category: 'graffiti' },
  { name: 'Slackey', family: "'Slackey', sans-serif", category: 'graffiti' },
  { name: 'Rubik Spray Paint', family: "'Rubik Spray Paint', sans-serif", category: 'graffiti' },
  { name: 'Rubik Marker Hatch', family: "'Rubik Marker Hatch', sans-serif", category: 'graffiti' },
  { name: 'Rubik Vinyl', family: "'Rubik Vinyl', sans-serif", category: 'graffiti' },
  { name: 'Rubik Wet Paint', family: "'Rubik Wet Paint', sans-serif", category: 'graffiti' },
  { name: 'Rubik Glitch', family: "'Rubik Glitch', sans-serif", category: 'graffiti' },
  { name: 'Rubik Bubbles', family: "'Rubik Bubbles', sans-serif", category: 'graffiti' },
  { name: 'Rubik Moonrocks', family: "'Rubik Moonrocks', sans-serif", category: 'graffiti' },
  { name: 'Rubik Puddles', family: "'Rubik Puddles', sans-serif", category: 'graffiti' },
  { name: 'Comic Neue', family: "'Comic Neue', cursive", category: 'graffiti' },
  { name: 'Fuzzy Bubbles', family: "'Fuzzy Bubbles', cursive", category: 'graffiti' },
  { name: 'Gloria Hallelujah', family: "'Gloria Hallelujah', cursive", category: 'graffiti' },
  { name: 'Just Me Again Down Here', family: "'Just Me Again Down Here', cursive", category: 'graffiti' },
  { name: 'Reenie Beanie', family: "'Reenie Beanie', cursive", category: 'graffiti' },
  { name: 'Rock Salt', family: "'Rock Salt', cursive", category: 'graffiti' },
  { name: 'Shadows Into Light', family: "'Shadows Into Light', cursive", category: 'graffiti' },
  { name: 'Shadows Into Light Two', family: "'Shadows Into Light Two', cursive", category: 'graffiti' },
  { name: 'Short Stack', family: "'Short Stack', cursive", category: 'graffiti' },
  { name: 'Sniglet', family: "'Sniglet', cursive", category: 'graffiti' },
  { name: 'Sue Ellen Francisco', family: "'Sue Ellen Francisco', cursive", category: 'graffiti' },
  { name: 'Sunshiney', family: "'Sunshiney', cursive", category: 'graffiti' },
  { name: 'Swanky and Moo Moo', family: "'Swanky and Moo Moo', cursive", category: 'graffiti' },
  { name: 'Waiting for the Sunrise', family: "'Waiting for the Sunrise', cursive", category: 'graffiti' },
  { name: 'Walter Turncoat', family: "'Walter Turncoat', cursive", category: 'graffiti' },
  { name: 'Schoolbell', family: "'Schoolbell', cursive", category: 'graffiti' },
  { name: 'Patrick Hand', family: "'Patrick Hand', cursive", category: 'graffiti' },
  { name: 'Patrick Hand SC', family: "'Patrick Hand SC', cursive", category: 'graffiti' },

  // =====================================================
  // HANDWRITTEN - Script and marker styles (60+ fonts)
  // =====================================================
  { name: 'Permanent Marker', family: "'Permanent Marker', cursive", category: 'handwritten' },
  { name: 'Luckiest Guy', family: "'Luckiest Guy', cursive", category: 'handwritten' },
  { name: 'Special Elite', family: "'Special Elite', system-ui", category: 'handwritten' },
  { name: 'Cabin Sketch', family: "'Cabin Sketch', sans-serif", category: 'handwritten' },
  { name: 'Fredericka the Great', family: "'Fredericka the Great', cursive", category: 'handwritten' },
  { name: 'Gochi Hand', family: "'Gochi Hand', cursive", category: 'handwritten' },
  { name: 'Kaushan Script', family: "'Kaushan Script', cursive", category: 'handwritten' },
  { name: 'Lobster', family: "'Lobster', cursive", category: 'handwritten' },
  { name: 'Lobster Two', family: "'Lobster Two', cursive", category: 'handwritten' },
  { name: 'Pacifico', family: "'Pacifico', cursive", category: 'handwritten' },
  { name: 'Sarina', family: "'Sarina', cursive", category: 'handwritten' },
  { name: 'Amatic SC', family: "'Amatic SC', cursive", category: 'handwritten' },
  { name: 'Architects Daughter', family: "'Architects Daughter', cursive", category: 'handwritten' },
  { name: 'Bad Script', family: "'Bad Script', cursive", category: 'handwritten' },
  { name: 'Caveat', family: "'Caveat', cursive", category: 'handwritten' },
  { name: 'Caveat Brush', family: "'Caveat Brush', cursive", category: 'handwritten' },
  { name: 'Cedarville Cursive', family: "'Cedarville Cursive', cursive", category: 'handwritten' },
  { name: 'Coming Soon', family: "'Coming Soon', cursive", category: 'handwritten' },
  { name: 'Covered By Your Grace', family: "'Covered By Your Grace', cursive", category: 'handwritten' },
  { name: 'Crafty Girls', family: "'Crafty Girls', cursive", category: 'handwritten' },
  { name: 'Dancing Script', family: "'Dancing Script', cursive", category: 'handwritten' },
  { name: 'Dawning of a New Day', family: "'Dawning of a New Day', cursive", category: 'handwritten' },
  { name: 'Delicious Handrawn', family: "'Delicious Handrawn', cursive", category: 'handwritten' },
  { name: 'Give You Glory', family: "'Give You Glory', cursive", category: 'handwritten' },
  { name: 'Great Vibes', family: "'Great Vibes', cursive", category: 'handwritten' },
  { name: 'Handlee', family: "'Handlee', cursive", category: 'handwritten' },
  { name: 'Homemade Apple', family: "'Homemade Apple', cursive", category: 'handwritten' },
  { name: 'Indie Flower', family: "'Indie Flower', cursive", category: 'handwritten' },
  { name: 'Itim', family: "'Itim', cursive", category: 'handwritten' },
  { name: 'Julee', family: "'Julee', cursive", category: 'handwritten' },
  { name: 'Just Another Hand', family: "'Just Another Hand', cursive", category: 'handwritten' },
  { name: 'Kalam', family: "'Kalam', cursive", category: 'handwritten' },
  { name: 'Kristi', family: "'Kristi', cursive", category: 'handwritten' },
  { name: 'La Belle Aurore', family: "'La Belle Aurore', cursive", category: 'handwritten' },
  { name: 'Leckerli One', family: "'Leckerli One', cursive", category: 'handwritten' },
  { name: 'Liu Jian Mao Cao', family: "'Liu Jian Mao Cao', cursive", category: 'handwritten' },
  { name: 'Long Cang', family: "'Long Cang', cursive", category: 'handwritten' },
  { name: 'Ma Shan Zheng', family: "'Ma Shan Zheng', cursive", category: 'handwritten' },
  { name: 'Mali', family: "'Mali', cursive", category: 'handwritten' },
  { name: 'Mansalva', family: "'Mansalva', cursive", category: 'handwritten' },
  { name: 'Marck Script', family: "'Marck Script', cursive", category: 'handwritten' },
  { name: 'Meddon', family: "'Meddon', cursive", category: 'handwritten' },
  { name: 'Meow Script', family: "'Meow Script', cursive", category: 'handwritten' },
  { name: 'Merienda', family: "'Merienda', cursive", category: 'handwritten' },
  { name: 'Merienda One', family: "'Merienda One', cursive", category: 'handwritten' },
  { name: 'Molle', family: "'Molle', cursive", category: 'handwritten' },
  { name: 'Monsieur La Doulaise', family: "'Monsieur La Doulaise', cursive", category: 'handwritten' },
  { name: 'Mr Dafoe', family: "'Mr Dafoe', cursive", category: 'handwritten' },
  { name: 'Mr De Haviland', family: "'Mr De Haviland', cursive", category: 'handwritten' },
  { name: 'Mrs Saint Delafield', family: "'Mrs Saint Delafield', cursive", category: 'handwritten' },
  { name: 'Mrs Sheppards', family: "'Mrs Sheppards', cursive", category: 'handwritten' },
  { name: 'Neucha', family: "'Neucha', cursive", category: 'handwritten' },
  { name: 'Niconne', family: "'Niconne', cursive", category: 'handwritten' },
  { name: 'Nothing You Could Do', family: "'Nothing You Could Do', cursive", category: 'handwritten' },
  { name: 'Oooh Baby', family: "'Oooh Baby', cursive", category: 'handwritten' },
  { name: 'Over the Rainbow', family: "'Over the Rainbow', cursive", category: 'handwritten' },
  { name: 'Paprika', family: "'Paprika', cursive", category: 'handwritten' },
  { name: 'Petit Formal Script', family: "'Petit Formal Script', cursive", category: 'handwritten' },
  { name: 'Pinyon Script', family: "'Pinyon Script', cursive", category: 'handwritten' },
  { name: 'Qwigley', family: "'Qwigley', cursive", category: 'handwritten' },
  { name: 'Rancho', family: "'Rancho', cursive", category: 'handwritten' },

  // =====================================================
  // SERIF - Elegant and classic (80+ fonts)
  // =====================================================
  { name: 'Cinzel', family: "'Cinzel', serif", category: 'serif' },
  { name: 'Cinzel Decorative', family: "'Cinzel Decorative', serif", category: 'serif' },
  { name: 'Playfair Display', family: "'Playfair Display', serif", category: 'serif' },
  { name: 'Playfair Display SC', family: "'Playfair Display SC', serif", category: 'serif' },
  { name: 'Graduate', family: "'Graduate', serif", category: 'serif' },
  { name: 'Ultra', family: "'Ultra', serif", category: 'serif' },
  { name: 'Abril Fatface', family: "'Abril Fatface', serif", category: 'serif' },
  { name: 'Berkshire Swash', family: "'Berkshire Swash', serif", category: 'serif' },
  { name: 'Diplomata SC', family: "'Diplomata SC', serif", category: 'serif' },
  { name: 'Germania One', family: "'Germania One', serif", category: 'serif' },
  { name: 'Libre Baskerville', family: "'Libre Baskerville', serif", category: 'serif' },
  { name: 'Libre Bodoni', family: "'Libre Bodoni', serif", category: 'serif' },
  { name: 'Libre Caslon Display', family: "'Libre Caslon Display', serif", category: 'serif' },
  { name: 'Libre Caslon Text', family: "'Libre Caslon Text', serif", category: 'serif' },
  { name: 'Lora', family: "'Lora', serif", category: 'serif' },
  { name: 'Merriweather', family: "'Merriweather', serif", category: 'serif' },
  { name: 'Noto Serif', family: "'Noto Serif', serif", category: 'serif' },
  { name: 'Noto Serif Display', family: "'Noto Serif Display', serif", category: 'serif' },
  { name: 'Old Standard TT', family: "'Old Standard TT', serif", category: 'serif' },
  { name: 'PT Serif', family: "'PT Serif', serif", category: 'serif' },
  { name: 'PT Serif Caption', family: "'PT Serif Caption', serif", category: 'serif' },
  { name: 'Roboto Serif', family: "'Roboto Serif', serif", category: 'serif' },
  { name: 'Roboto Slab', family: "'Roboto Slab', serif", category: 'serif' },
  { name: 'Rokkitt', family: "'Rokkitt', serif", category: 'serif' },
  { name: 'Source Serif 4', family: "'Source Serif 4', serif", category: 'serif' },
  { name: 'Source Serif Pro', family: "'Source Serif Pro', serif", category: 'serif' },
  { name: 'Spectral', family: "'Spectral', serif", category: 'serif' },
  { name: 'Spectral SC', family: "'Spectral SC', serif", category: 'serif' },
  { name: 'Zilla Slab', family: "'Zilla Slab', serif", category: 'serif' },
  { name: 'Zilla Slab Highlight', family: "'Zilla Slab Highlight', serif", category: 'serif' },
  { name: 'Cormorant', family: "'Cormorant', serif", category: 'serif' },
  { name: 'Cormorant Garamond', family: "'Cormorant Garamond', serif", category: 'serif' },
  { name: 'Cormorant Infant', family: "'Cormorant Infant', serif", category: 'serif' },
  { name: 'Cormorant SC', family: "'Cormorant SC', serif", category: 'serif' },
  { name: 'Cormorant Unicase', family: "'Cormorant Unicase', serif", category: 'serif' },
  { name: 'Cormorant Upright', family: "'Cormorant Upright', serif", category: 'serif' },
  { name: 'Cardo', family: "'Cardo', serif", category: 'serif' },
  { name: 'Crimson Pro', family: "'Crimson Pro', serif", category: 'serif' },
  { name: 'Crimson Text', family: "'Crimson Text', serif", category: 'serif' },
  { name: 'Domine', family: "'Domine', serif", category: 'serif' },
  { name: 'EB Garamond', family: "'EB Garamond', serif", category: 'serif' },
  { name: 'Faustina', family: "'Faustina', serif", category: 'serif' },
  { name: 'Gelasio', family: "'Gelasio', serif", category: 'serif' },
  { name: 'Gentium Book Plus', family: "'Gentium Book Plus', serif", category: 'serif' },
  { name: 'Gilda Display', family: "'Gilda Display', serif", category: 'serif' },
  { name: 'Headland One', family: "'Headland One', serif", category: 'serif' },
  { name: 'IBM Plex Serif', family: "'IBM Plex Serif', serif", category: 'serif' },
  { name: 'Imbue', family: "'Imbue', serif", category: 'serif' },
  { name: 'Josefin Slab', family: "'Josefin Slab', serif", category: 'serif' },
  { name: 'Judson', family: "'Judson', serif", category: 'serif' },
  { name: 'Literata', family: "'Literata', serif", category: 'serif' },
  { name: 'Lustria', family: "'Lustria', serif", category: 'serif' },
  { name: 'Marcellus', family: "'Marcellus', serif", category: 'serif' },
  { name: 'Marcellus SC', family: "'Marcellus SC', serif", category: 'serif' },
  { name: 'Mate', family: "'Mate', serif", category: 'serif' },
  { name: 'Mate SC', family: "'Mate SC', serif", category: 'serif' },
  { name: 'Neuton', family: "'Neuton', serif", category: 'serif' },
  { name: 'Noticia Text', family: "'Noticia Text', serif", category: 'serif' },
  { name: 'Oranienbaum', family: "'Oranienbaum', serif", category: 'serif' },
  { name: 'Petrona', family: "'Petrona', serif", category: 'serif' },
  { name: 'Prata', family: "'Prata', serif", category: 'serif' },
  { name: 'Quando', family: "'Quando', serif", category: 'serif' },
  { name: 'Radley', family: "'Radley', serif", category: 'serif' },
  { name: 'Rosarivo', family: "'Rosarivo', serif", category: 'serif' },
  { name: 'Rufina', family: "'Rufina', serif", category: 'serif' },
  { name: 'Sahitya', family: "'Sahitya', serif", category: 'serif' },
  { name: 'Sanchez', family: "'Sanchez', serif", category: 'serif' },
  { name: 'Sorts Mill Goudy', family: "'Sorts Mill Goudy', serif", category: 'serif' },
  { name: 'Stoke', family: "'Stoke', serif", category: 'serif' },
  { name: 'Sumana', family: "'Sumana', serif", category: 'serif' },
  { name: 'Suranna', family: "'Suranna', serif", category: 'serif' },
  { name: 'Suravaram', family: "'Suravaram', serif", category: 'serif' },
  { name: 'Taviraj', family: "'Taviraj', serif", category: 'serif' },
  { name: 'Trirong', family: "'Trirong', serif", category: 'serif' },
  { name: 'Unna', family: "'Unna', serif", category: 'serif' },
  { name: 'Vesper Libre', family: "'Vesper Libre', serif", category: 'serif' },
  { name: 'Vidaloka', family: "'Vidaloka', serif", category: 'serif' },
  { name: 'Vollkorn', family: "'Vollkorn', serif", category: 'serif' },
  { name: 'Vollkorn SC', family: "'Vollkorn SC', serif", category: 'serif' },
  { name: 'Yaldevi', family: "'Yaldevi', serif", category: 'serif' },
  { name: 'Young Serif', family: "'Young Serif', serif", category: 'serif' },

  // =====================================================
  // SANS - Clean but bold (100+ fonts)
  // =====================================================
  { name: 'Gruppo', family: "'Gruppo', sans-serif", category: 'sans' },
  { name: 'Black Han Sans', family: "'Black Han Sans', sans-serif", category: 'sans' },
  { name: 'Comfortaa', family: "'Comfortaa', sans-serif", category: 'sans' },
  { name: 'Dosis', family: "'Dosis', sans-serif", category: 'sans' },
  { name: 'Fredoka', family: "'Fredoka', sans-serif", category: 'sans' },
  { name: 'Lemonada', family: "'Lemonada', sans-serif", category: 'sans' },
  { name: 'Rampart One', family: "'Rampart One', sans-serif", category: 'sans' },
  { name: 'Kelly Slab', family: "'Kelly Slab', serif", category: 'sans' },
  { name: 'Ceviche One', family: "'Ceviche One', sans-serif", category: 'sans' },
  { name: 'Caesar Dressing', family: "'Caesar Dressing', sans-serif", category: 'sans' },
  { name: 'Shojumaru', family: "'Shojumaru', sans-serif", category: 'sans' },
  { name: 'ABeeZee', family: "'ABeeZee', sans-serif", category: 'sans' },
  { name: 'Abel', family: "'Abel', sans-serif", category: 'sans' },
  { name: 'Acme', family: "'Acme', sans-serif", category: 'sans' },
  { name: 'Albert Sans', family: "'Albert Sans', sans-serif", category: 'sans' },
  { name: 'Alegreya Sans', family: "'Alegreya Sans', sans-serif", category: 'sans' },
  { name: 'Alegreya Sans SC', family: "'Alegreya Sans SC', sans-serif", category: 'sans' },
  { name: 'Almarai', family: "'Almarai', sans-serif", category: 'sans' },
  { name: 'Amiko', family: "'Amiko', sans-serif", category: 'sans' },
  { name: 'Andika', family: "'Andika', sans-serif", category: 'sans' },
  { name: 'Archivo', family: "'Archivo', sans-serif", category: 'sans' },
  { name: 'Arimo', family: "'Arimo', sans-serif", category: 'sans' },
  { name: 'Arsenal', family: "'Arsenal', sans-serif", category: 'sans' },
  { name: 'Asap', family: "'Asap', sans-serif", category: 'sans' },
  { name: 'Asap Condensed', family: "'Asap Condensed', sans-serif", category: 'sans' },
  { name: 'Assistant', family: "'Assistant', sans-serif", category: 'sans' },
  { name: 'Atkinson Hyperlegible', family: "'Atkinson Hyperlegible', sans-serif", category: 'sans' },
  { name: 'B612', family: "'B612', sans-serif", category: 'sans' },
  { name: 'Be Vietnam Pro', family: "'Be Vietnam Pro', sans-serif", category: 'sans' },
  { name: 'Bitter', family: "'Bitter', serif", category: 'sans' },
  { name: 'Cabin', family: "'Cabin', sans-serif", category: 'sans' },
  { name: 'Cabin Condensed', family: "'Cabin Condensed', sans-serif", category: 'sans' },
  { name: 'Cairo', family: "'Cairo', sans-serif", category: 'sans' },
  { name: 'Cantarell', family: "'Cantarell', sans-serif", category: 'sans' },
  { name: 'Catamaran', family: "'Catamaran', sans-serif", category: 'sans' },
  { name: 'Chivo', family: "'Chivo', sans-serif", category: 'sans' },
  { name: 'Commissioner', family: "'Commissioner', sans-serif", category: 'sans' },
  { name: 'Cuprum', family: "'Cuprum', sans-serif", category: 'sans' },
  { name: 'DM Sans', family: "'DM Sans', sans-serif", category: 'sans' },
  { name: 'Didact Gothic', family: "'Didact Gothic', sans-serif", category: 'sans' },
  { name: 'Encode Sans', family: "'Encode Sans', sans-serif", category: 'sans' },
  { name: 'Encode Sans Condensed', family: "'Encode Sans Condensed', sans-serif", category: 'sans' },
  { name: 'Encode Sans Expanded', family: "'Encode Sans Expanded', sans-serif", category: 'sans' },
  { name: 'Encode Sans SC', family: "'Encode Sans SC', sans-serif", category: 'sans' },
  { name: 'Encode Sans Semi Condensed', family: "'Encode Sans Semi Condensed', sans-serif", category: 'sans' },
  { name: 'Encode Sans Semi Expanded', family: "'Encode Sans Semi Expanded', sans-serif", category: 'sans' },
  { name: 'Epilogue', family: "'Epilogue', sans-serif", category: 'sans' },
  { name: 'Exo', family: "'Exo', sans-serif", category: 'sans' },
  { name: 'Figtree', family: "'Figtree', sans-serif", category: 'sans' },
  { name: 'Fira Sans Condensed', family: "'Fira Sans Condensed', sans-serif", category: 'sans' },
  { name: 'Fira Sans Extra Condensed', family: "'Fira Sans Extra Condensed', sans-serif", category: 'sans' },
  { name: 'Geologica', family: "'Geologica', sans-serif", category: 'sans' },
  { name: 'Gothic A1', family: "'Gothic A1', sans-serif", category: 'sans' },
  { name: 'Hanken Grotesk', family: "'Hanken Grotesk', sans-serif", category: 'sans' },
  { name: 'Hind', family: "'Hind', sans-serif", category: 'sans' },
  { name: 'Hind Guntur', family: "'Hind Guntur', sans-serif", category: 'sans' },
  { name: 'Hind Madurai', family: "'Hind Madurai', sans-serif", category: 'sans' },
  { name: 'Hind Siliguri', family: "'Hind Siliguri', sans-serif", category: 'sans' },
  { name: 'Hind Vadodara', family: "'Hind Vadodara', sans-serif", category: 'sans' },
  { name: 'IBM Plex Sans', family: "'IBM Plex Sans', sans-serif", category: 'sans' },
  { name: 'IBM Plex Sans Condensed', family: "'IBM Plex Sans Condensed', sans-serif", category: 'sans' },
  { name: 'Inter', family: "'Inter', sans-serif", category: 'sans' },
  { name: 'Inter Tight', family: "'Inter Tight', sans-serif", category: 'sans' },
  { name: 'Jost', family: "'Jost', sans-serif", category: 'sans' },
  { name: 'Josefin Sans', family: "'Josefin Sans', sans-serif", category: 'sans' },
  { name: 'Karla', family: "'Karla', sans-serif", category: 'sans' },
  { name: 'Kumbh Sans', family: "'Kumbh Sans', sans-serif", category: 'sans' },
  { name: 'Lato', family: "'Lato', sans-serif", category: 'sans' },
  { name: 'League Spartan', family: "'League Spartan', sans-serif", category: 'sans' },
  { name: 'Lexend', family: "'Lexend', sans-serif", category: 'sans' },
  { name: 'Libre Franklin', family: "'Libre Franklin', sans-serif", category: 'sans' },
  { name: 'Manrope', family: "'Manrope', sans-serif", category: 'sans' },
  { name: 'Maven Pro', family: "'Maven Pro', sans-serif", category: 'sans' },
  { name: 'Merriweather Sans', family: "'Merriweather Sans', sans-serif", category: 'sans' },
  { name: 'Montserrat', family: "'Montserrat', sans-serif", category: 'sans' },
  { name: 'Montserrat Alternates', family: "'Montserrat Alternates', sans-serif", category: 'sans' },
  { name: 'Mulish', family: "'Mulish', sans-serif", category: 'sans' },
  { name: 'Mukta', family: "'Mukta', sans-serif", category: 'sans' },
  { name: 'Nanum Gothic', family: "'Nanum Gothic', sans-serif", category: 'sans' },
  { name: 'Nunito', family: "'Nunito', sans-serif", category: 'sans' },
  { name: 'Nunito Sans', family: "'Nunito Sans', sans-serif", category: 'sans' },
  { name: 'Open Sans', family: "'Open Sans', sans-serif", category: 'sans' },
  { name: 'Outfit', family: "'Outfit', sans-serif", category: 'sans' },
  { name: 'Overpass', family: "'Overpass', sans-serif", category: 'sans' },
  { name: 'Oxygen', family: "'Oxygen', sans-serif", category: 'sans' },
  { name: 'PT Sans', family: "'PT Sans', sans-serif", category: 'sans' },
  { name: 'PT Sans Caption', family: "'PT Sans Caption', sans-serif", category: 'sans' },
  { name: 'PT Sans Narrow', family: "'PT Sans Narrow', sans-serif", category: 'sans' },
  { name: 'Poppins', family: "'Poppins', sans-serif", category: 'sans' },
  { name: 'Public Sans', family: "'Public Sans', sans-serif", category: 'sans' },
  { name: 'Questrial', family: "'Questrial', sans-serif", category: 'sans' },
  { name: 'Quicksand', family: "'Quicksand', sans-serif", category: 'sans' },
  { name: 'Raleway', family: "'Raleway', sans-serif", category: 'sans' },
  { name: 'Red Hat Display', family: "'Red Hat Display', sans-serif", category: 'sans' },
  { name: 'Red Hat Text', family: "'Red Hat Text', sans-serif", category: 'sans' },
  { name: 'Roboto', family: "'Roboto', sans-serif", category: 'sans' },
  { name: 'Roboto Condensed', family: "'Roboto Condensed', sans-serif", category: 'sans' },
  { name: 'Roboto Flex', family: "'Roboto Flex', sans-serif", category: 'sans' },
  { name: 'Rubik', family: "'Rubik', sans-serif", category: 'sans' },
  { name: 'Ruda', family: "'Ruda', sans-serif", category: 'sans' },
  { name: 'Saira', family: "'Saira', sans-serif", category: 'sans' },
  { name: 'Signika', family: "'Signika', sans-serif", category: 'sans' },
  { name: 'Signika Negative', family: "'Signika Negative', sans-serif", category: 'sans' },
  { name: 'Sora', family: "'Sora', sans-serif", category: 'sans' },
  { name: 'Source Sans 3', family: "'Source Sans 3', sans-serif", category: 'sans' },
  { name: 'Space Grotesk', family: "'Space Grotesk', sans-serif", category: 'sans' },
  { name: 'Syne', family: "'Syne', sans-serif", category: 'sans' },
  { name: 'Titillium Web', family: "'Titillium Web', sans-serif", category: 'sans' },
  { name: 'Ubuntu', family: "'Ubuntu', sans-serif", category: 'sans' },
  { name: 'Ubuntu Condensed', family: "'Ubuntu Condensed', sans-serif", category: 'sans' },
  { name: 'Urbanist', family: "'Urbanist', sans-serif", category: 'sans' },
  { name: 'Varela Round', family: "'Varela Round', sans-serif", category: 'sans' },
  { name: 'Work Sans', family: "'Work Sans', sans-serif", category: 'sans' },
  { name: 'Yantramanav', family: "'Yantramanav', sans-serif", category: 'sans' },
  { name: 'Zen Kaku Gothic New', family: "'Zen Kaku Gothic New', sans-serif", category: 'sans' },

  // =====================================================
  // MONO - Technical and code-like (25+ fonts)
  // =====================================================
  { name: 'Fira Code', family: "'Fira Code', monospace", category: 'mono' },
  { name: 'JetBrains Mono', family: "'JetBrains Mono', monospace", category: 'mono' },
  { name: 'Source Code Pro', family: "'Source Code Pro', monospace", category: 'mono' },
  { name: 'Space Mono', family: "'Space Mono', monospace", category: 'mono' },
  { name: 'Ubuntu Mono', family: "'Ubuntu Mono', monospace", category: 'mono' },
  { name: 'Anonymous Pro', family: "'Anonymous Pro', monospace", category: 'mono' },
  { name: 'B612 Mono', family: "'B612 Mono', monospace", category: 'mono' },
  { name: 'Cousine', family: "'Cousine', monospace", category: 'mono' },
  { name: 'DM Mono', family: "'DM Mono', monospace", category: 'mono' },
  { name: 'Fira Mono', family: "'Fira Mono', monospace", category: 'mono' },
  { name: 'Noto Sans Mono', family: "'Noto Sans Mono', monospace", category: 'mono' },
  { name: 'Oxygen Mono', family: "'Oxygen Mono', monospace", category: 'mono' },

  // =====================================================
  // ELEGANT - Luxury and sophisticated (40+ fonts)
  // =====================================================
  { name: 'Alex Brush', family: "'Alex Brush', cursive", category: 'elegant' },
  { name: 'Allura', family: "'Allura', cursive", category: 'elegant' },
  { name: 'Corinthia', family: "'Corinthia', cursive", category: 'elegant' },
  { name: 'Herr Von Muellerhoff', family: "'Herr Von Muellerhoff', cursive", category: 'elegant' },
  { name: 'Hurricane', family: "'Hurricane', cursive", category: 'elegant' },
  { name: 'Imperial Script', family: "'Imperial Script', cursive", category: 'elegant' },
  { name: 'Island Moments', family: "'Island Moments', cursive", category: 'elegant' },
  { name: 'Italiana', family: "'Italiana', serif", category: 'elegant' },
  { name: 'Lavishly Yours', family: "'Lavishly Yours', cursive", category: 'elegant' },
  { name: 'Licorice', family: "'Licorice', cursive", category: 'elegant' },
  { name: 'Love Light', family: "'Love Light', cursive", category: 'elegant' },
  { name: 'Luxurious Roman', family: "'Luxurious Roman', cursive", category: 'elegant' },
  { name: 'Luxurious Script', family: "'Luxurious Script', cursive", category: 'elegant' },
  { name: 'Mea Culpa', family: "'Mea Culpa', cursive", category: 'elegant' },
  { name: 'Oleo Script', family: "'Oleo Script', cursive", category: 'elegant' },
  { name: 'Oleo Script Swash Caps', family: "'Oleo Script Swash Caps', cursive", category: 'elegant' },
  { name: 'Oooh Baby', family: "'Oooh Baby', cursive", category: 'elegant' },
  { name: 'Parisienne', family: "'Parisienne', cursive", category: 'elegant' },
  { name: 'Passions Conflict', family: "'Passions Conflict', cursive", category: 'elegant' },
  { name: 'Petemoss', family: "'Petemoss', cursive", category: 'elegant' },
  { name: 'Philosopher', family: "'Philosopher', sans-serif", category: 'elegant' },
  { name: 'Praise', family: "'Praise', cursive", category: 'elegant' },
  { name: 'Princess Sofia', family: "'Princess Sofia', cursive", category: 'elegant' },
  { name: 'Rouge Script', family: "'Rouge Script', cursive", category: 'elegant' },
  { name: 'Sacramento', family: "'Sacramento', cursive", category: 'elegant' },
  { name: 'Sail', family: "'Sail', cursive", category: 'elegant' },
  { name: 'Satisfy', family: "'Satisfy', cursive", category: 'elegant' },
  { name: 'Send Flowers', family: "'Send Flowers', cursive", category: 'elegant' },
  { name: 'Shadows Into Light', family: "'Shadows Into Light', cursive", category: 'elegant' },
  { name: 'Sofia', family: "'Sofia', cursive", category: 'elegant' },
  { name: 'Style Script', family: "'Style Script', cursive", category: 'elegant' },
  { name: 'Tangerine', family: "'Tangerine', cursive", category: 'elegant' },
  { name: 'The Nautigal', family: "'The Nautigal', cursive", category: 'elegant' },
  { name: 'Vujahday Script', family: "'Vujahday Script', cursive", category: 'elegant' },
  { name: 'Waterfall', family: "'Waterfall', cursive", category: 'elegant' },
  { name: 'WindSong', family: "'WindSong', cursive", category: 'elegant' },

  // =====================================================
  // FUTURISTIC - Sci-fi and tech (35+ fonts)
  // =====================================================
  { name: 'Oxanium', family: "'Oxanium', sans-serif", category: 'futuristic' },
  { name: 'Rajdhani', family: "'Rajdhani', sans-serif", category: 'futuristic' },
  { name: 'Rationale', family: "'Rationale', sans-serif", category: 'futuristic' },
  { name: 'Redo', family: "'Redo', sans-serif", category: 'futuristic' },
  { name: 'Righteous', family: "'Righteous', sans-serif", category: 'futuristic' },
  { name: 'Russo One', family: "'Russo One', sans-serif", category: 'futuristic' },
  { name: 'Saira', family: "'Saira', sans-serif", category: 'futuristic' },
  { name: 'Sarpanch', family: "'Sarpanch', sans-serif", category: 'futuristic' },
  { name: 'Share', family: "'Share', sans-serif", category: 'futuristic' },
  { name: 'Share Tech', family: "'Share Tech', sans-serif", category: 'futuristic' },
  { name: 'Exo 2', family: "'Exo 2', sans-serif", category: 'futuristic' },
  { name: 'Chakra Petch', family: "'Chakra Petch', sans-serif", category: 'futuristic' },
  { name: 'Coda', family: "'Coda', sans-serif", category: 'futuristic' },
  { name: 'Electrolize', family: "'Electrolize', sans-serif", category: 'futuristic' },
  { name: 'Geo', family: "'Geo', sans-serif", category: 'futuristic' },
  { name: 'Gruppo', family: "'Gruppo', sans-serif", category: 'futuristic' },
  { name: 'Iceland', family: "'Iceland', sans-serif", category: 'futuristic' },
  { name: 'Jura', family: "'Jura', sans-serif", category: 'futuristic' },
  { name: 'Kanit', family: "'Kanit', sans-serif", category: 'futuristic' },
  { name: 'Keania One', family: "'Keania One', sans-serif", category: 'futuristic' },
  { name: 'Michroma', family: "'Michroma', sans-serif", category: 'futuristic' },
  { name: 'Orbitron', family: "'Orbitron', sans-serif", category: 'futuristic' },
  { name: 'Teko', family: "'Teko', sans-serif", category: 'futuristic' },
  { name: 'Turret Road', family: "'Turret Road', sans-serif", category: 'futuristic' },
  { name: 'Zen Dots', family: "'Zen Dots', cursive", category: 'futuristic' },
  { name: 'Bruno Ace', family: "'Bruno Ace', cursive", category: 'futuristic' },
  { name: 'Bruno Ace SC', family: "'Bruno Ace SC', cursive", category: 'futuristic' },
  { name: 'Tomorrow', family: "'Tomorrow', sans-serif", category: 'futuristic' },
  { name: 'Advent Pro', family: "'Advent Pro', sans-serif", category: 'futuristic' },
  { name: 'Audiowide', family: "'Audiowide', sans-serif", category: 'futuristic' },

  // =====================================================
  // VINTAGE - Classic and retro (40+ fonts)
  // =====================================================
  { name: 'Special Elite', family: "'Special Elite', cursive", category: 'vintage' },
  { name: 'Arbutus Slab', family: "'Arbutus Slab', serif", category: 'vintage' },
  { name: 'Bellefair', family: "'Bellefair', serif", category: 'vintage' },
  { name: 'BioRhyme', family: "'BioRhyme', serif", category: 'vintage' },
  { name: 'BioRhyme Expanded', family: "'BioRhyme Expanded', serif", category: 'vintage' },
  { name: 'Corben', family: "'Corben', cursive", category: 'vintage' },
  { name: 'Coustard', family: "'Coustard', serif", category: 'vintage' },
  { name: 'Cutive', family: "'Cutive', serif", category: 'vintage' },
  { name: 'Enriqueta', family: "'Enriqueta', serif", category: 'vintage' },
  { name: 'Fanwood Text', family: "'Fanwood Text', serif", category: 'vintage' },
  { name: 'Fenix', family: "'Fenix', serif", category: 'vintage' },
  { name: 'Forum', family: "'Forum', cursive", category: 'vintage' },
  { name: 'Glass Antiqua', family: "'Glass Antiqua', cursive", category: 'vintage' },
  { name: 'Goudy Bookletter 1911', family: "'Goudy Bookletter 1911', serif", category: 'vintage' },
  { name: 'Gupter', family: "'Gupter', serif", category: 'vintage' },
  { name: 'Habibi', family: "'Habibi', serif", category: 'vintage' },
  { name: 'Jomhuria', family: "'Jomhuria', serif", category: 'vintage' },
  { name: 'Junge', family: "'Junge', serif", category: 'vintage' },
  { name: 'Kameron', family: "'Kameron', serif", category: 'vintage' },
  { name: 'Kotta One', family: "'Kotta One', serif", category: 'vintage' },
  { name: 'Ledger', family: "'Ledger', serif", category: 'vintage' },
  { name: 'Linden Hill', family: "'Linden Hill', serif", category: 'vintage' },
  { name: 'Lora', family: "'Lora', serif", category: 'vintage' },
  { name: 'Newsreader', family: "'Newsreader', serif", category: 'vintage' },
  { name: 'Nixie One', family: "'Nixie One', cursive", category: 'vintage' },
  { name: 'Oranienbaum', family: "'Oranienbaum', serif", category: 'vintage' },
  { name: 'Piazzolla', family: "'Piazzolla', serif", category: 'vintage' },
  { name: 'Poly', family: "'Poly', serif", category: 'vintage' },
  { name: 'Port Lligat Slab', family: "'Port Lligat Slab', serif", category: 'vintage' },
  { name: 'Quintessential', family: "'Quintessential', cursive", category: 'vintage' },
  { name: 'Ramaraja', family: "'Ramaraja', serif", category: 'vintage' },
  { name: 'Rozha One', family: "'Rozha One', serif", category: 'vintage' },
  { name: 'Sansita Swashed', family: "'Sansita Swashed', cursive", category: 'vintage' },

  // =====================================================
  // BRUSH - Hand-painted and artistic (35+ fonts)
  // =====================================================
  { name: 'Akronim', family: "'Akronim', cursive", category: 'brush' },
  { name: 'Arizonia', family: "'Arizonia', cursive", category: 'brush' },
  { name: 'Ballet', family: "'Ballet', cursive", category: 'brush' },
  { name: 'Bilbo', family: "'Bilbo', cursive", category: 'brush' },
  { name: 'Bilbo Swash Caps', family: "'Bilbo Swash Caps', cursive", category: 'brush' },
  { name: 'Birthstone', family: "'Birthstone', cursive", category: 'brush' },
  { name: 'Birthstone Bounce', family: "'Birthstone Bounce', cursive", category: 'brush' },
  { name: 'Bonheur Royale', family: "'Bonheur Royale', cursive", category: 'brush' },
  { name: 'Clicker Script', family: "'Clicker Script', cursive", category: 'brush' },
  { name: 'Courgette', family: "'Courgette', cursive", category: 'brush' },
  { name: 'Croissant One', family: "'Croissant One', cursive", category: 'brush' },
  { name: 'Damion', family: "'Damion', cursive", category: 'brush' },
  { name: 'Eagle Lake', family: "'Eagle Lake', cursive", category: 'brush' },
  { name: 'Engagement', family: "'Engagement', cursive", category: 'brush' },
  { name: 'Euphoria Script', family: "'Euphoria Script', cursive", category: 'brush' },
  { name: 'Felipa', family: "'Felipa', cursive", category: 'brush' },
  { name: 'Festive', family: "'Festive', cursive", category: 'brush' },
  { name: 'Fondamento', family: "'Fondamento', cursive", category: 'brush' },
  { name: 'Grape Nuts', family: "'Grape Nuts', cursive", category: 'brush' },
  { name: 'Great Vibes', family: "'Great Vibes', cursive", category: 'brush' },
  { name: 'Gwendolyn', family: "'Gwendolyn', cursive", category: 'brush' },
  { name: 'Hachi Maru Pop', family: "'Hachi Maru Pop', cursive", category: 'brush' },
  { name: 'Klee One', family: "'Klee One', cursive", category: 'brush' },
  { name: 'Licorice', family: "'Licorice', cursive", category: 'brush' },
  { name: 'Lovers Quarrel', family: "'Lovers Quarrel', cursive", category: 'brush' },
  { name: 'Macondo', family: "'Macondo', cursive", category: 'brush' },
  { name: 'Macondo Swash Caps', family: "'Macondo Swash Caps', cursive", category: 'brush' },
  { name: 'Marck Script', family: "'Marck Script', cursive", category: 'brush' },
  { name: 'Miss Fajardose', family: "'Miss Fajardose', cursive", category: 'brush' },
  { name: 'Moon Dance', family: "'Moon Dance', cursive", category: 'brush' },
  { name: 'Norican', family: "'Norican', cursive", category: 'brush' },

  // =====================================================
  // STENCIL - Military and industrial (20+ fonts)
  // =====================================================
  { name: 'Allerta Stencil', family: "'Allerta Stencil', sans-serif", category: 'stencil' },
  { name: 'Big Shoulders Stencil Display', family: "'Big Shoulders Stencil Display', sans-serif", category: 'stencil' },
  { name: 'Big Shoulders Stencil Text', family: "'Big Shoulders Stencil Text', sans-serif", category: 'stencil' },
  { name: 'Diplomata', family: "'Diplomata', serif", category: 'stencil' },
  { name: 'Saira Stencil One', family: "'Saira Stencil One', sans-serif", category: 'stencil' },
  { name: 'Stardos Stencil', family: "'Stardos Stencil', sans-serif", category: 'stencil' },
  { name: 'Stint Ultra Condensed', family: "'Stint Ultra Condensed', serif", category: 'stencil' },
  { name: 'Graduate', family: "'Graduate', serif", category: 'stencil' },
  { name: 'Marcellus SC', family: "'Marcellus SC', serif", category: 'stencil' },
  { name: 'Oleo Script', family: "'Oleo Script', cursive", category: 'stencil' },
  { name: 'Plaster', family: "'Plaster', sans-serif", category: 'stencil' },
  { name: 'Rampart One', family: "'Rampart One', sans-serif", category: 'stencil' },
  { name: 'Rye', family: "'Rye', serif", category: 'stencil' },
  { name: 'Sancreek', family: "'Sancreek', serif", category: 'stencil' },
  { name: 'Trade Winds', family: "'Trade Winds', cursive", category: 'stencil' },

  // =====================================================
  // OUTLINE - Hollow and outlined (15+ fonts)
  // =====================================================
  { name: 'Bungee Outline', family: "'Bungee Outline', sans-serif", category: 'outline' },
  { name: 'Blaka Hollow', family: "'Blaka Hollow', sans-serif", category: 'outline' },
  { name: 'Londrina Outline', family: "'Londrina Outline', cursive", category: 'outline' },
  { name: 'Londrina Shadow', family: "'Londrina Shadow', cursive", category: 'outline' },
  { name: 'Big Shoulders Inline Display', family: "'Big Shoulders Inline Display', sans-serif", category: 'outline' },
  { name: 'Big Shoulders Inline Text', family: "'Big Shoulders Inline Text', sans-serif", category: 'outline' },
  { name: 'Bungee Inline', family: "'Bungee Inline', sans-serif", category: 'outline' },
  { name: 'Fascinate Inline', family: "'Fascinate Inline', cursive", category: 'outline' },
  { name: 'Codystar', family: "'Codystar', sans-serif", category: 'outline' },
  { name: 'Jacques Francois Shadow', family: "'Jacques Francois Shadow', serif", category: 'outline' },
  { name: 'Monoton', family: "'Monoton', sans-serif", category: 'outline' },
  { name: 'Nova Cut', family: "'Nova Cut', cursive", category: 'outline' },
  { name: 'Rubik Doodle Shadow', family: "'Rubik Doodle Shadow', sans-serif", category: 'outline' },
  { name: 'Zilla Slab Highlight', family: "'Zilla Slab Highlight', serif", category: 'outline' },

  // =====================================================
  // ROUNDED - Soft and friendly (25+ fonts)
  // =====================================================
  { name: 'Comfortaa', family: "'Comfortaa', sans-serif", category: 'rounded' },
  { name: 'Fredoka', family: "'Fredoka', sans-serif", category: 'rounded' },
  { name: 'Nunito', family: "'Nunito', sans-serif", category: 'rounded' },
  { name: 'Quicksand', family: "'Quicksand', sans-serif", category: 'rounded' },
  { name: 'Varela Round', family: "'Varela Round', sans-serif", category: 'rounded' },
  { name: 'M PLUS Rounded 1c', family: "'M PLUS Rounded 1c', sans-serif", category: 'rounded' },
  { name: 'Patrick Hand', family: "'Patrick Hand', cursive", category: 'rounded' },
  { name: 'Sniglet', family: "'Sniglet', cursive", category: 'rounded' },
  { name: 'Baloo 2', family: "'Baloo 2', cursive", category: 'rounded' },
  { name: 'Capriola', family: "'Capriola', sans-serif", category: 'rounded' },
  { name: 'Chewy', family: "'Chewy', sans-serif", category: 'rounded' },
  { name: 'Concert One', family: "'Concert One', sans-serif", category: 'rounded' },
  { name: 'Dosis', family: "'Dosis', sans-serif", category: 'rounded' },
  { name: 'Fuzzy Bubbles', family: "'Fuzzy Bubbles', cursive", category: 'rounded' },
  { name: 'Itim', family: "'Itim', cursive", category: 'rounded' },
  { name: 'Lexend', family: "'Lexend', sans-serif", category: 'rounded' },
  { name: 'Mali', family: "'Mali', cursive", category: 'rounded' },
  { name: 'Rubik', family: "'Rubik', sans-serif", category: 'rounded' },
  { name: 'Shantell Sans', family: "'Shantell Sans', cursive", category: 'rounded' },
  { name: 'Short Stack', family: "'Short Stack', cursive", category: 'rounded' },
  { name: 'Signika', family: "'Signika', sans-serif", category: 'rounded' },
  { name: 'Cabin', family: "'Cabin', sans-serif", category: 'rounded' },

  // =====================================================
  // CONDENSED - Tall and narrow (30+ fonts)
  // =====================================================
  { name: 'Archivo Narrow', family: "'Archivo Narrow', sans-serif", category: 'condensed' },
  { name: 'Barlow Condensed', family: "'Barlow Condensed', sans-serif", category: 'condensed' },
  { name: 'Barlow Semi Condensed', family: "'Barlow Semi Condensed', sans-serif", category: 'condensed' },
  { name: 'Bebas Neue', family: "'Bebas Neue', sans-serif", category: 'condensed' },
  { name: 'Cabin Condensed', family: "'Cabin Condensed', sans-serif", category: 'condensed' },
  { name: 'Encode Sans Condensed', family: "'Encode Sans Condensed', sans-serif", category: 'condensed' },
  { name: 'Encode Sans Semi Condensed', family: "'Encode Sans Semi Condensed', sans-serif", category: 'condensed' },
  { name: 'Fira Sans Condensed', family: "'Fira Sans Condensed', sans-serif", category: 'condensed' },
  { name: 'Fira Sans Extra Condensed', family: "'Fira Sans Extra Condensed', sans-serif", category: 'condensed' },
  { name: 'Fjalla One', family: "'Fjalla One', sans-serif", category: 'condensed' },
  { name: 'IBM Plex Sans Condensed', family: "'IBM Plex Sans Condensed', sans-serif", category: 'condensed' },
  { name: 'Oswald', family: "'Oswald', sans-serif", category: 'condensed' },
  { name: 'Pathway Gothic One', family: "'Pathway Gothic One', sans-serif", category: 'condensed' },
  { name: 'PT Sans Narrow', family: "'PT Sans Narrow', sans-serif", category: 'condensed' },
  { name: 'Roboto Condensed', family: "'Roboto Condensed', sans-serif", category: 'condensed' },
  { name: 'Saira Condensed', family: "'Saira Condensed', sans-serif", category: 'condensed' },
  { name: 'Saira Extra Condensed', family: "'Saira Extra Condensed', sans-serif", category: 'condensed' },
  { name: 'Saira Semi Condensed', family: "'Saira Semi Condensed', sans-serif", category: 'condensed' },
  { name: 'Teko', family: "'Teko', sans-serif", category: 'condensed' },
  { name: 'Ubuntu Condensed', family: "'Ubuntu Condensed', sans-serif", category: 'condensed' },
  { name: 'Yanone Kaffeesatz', family: "'Yanone Kaffeesatz', sans-serif", category: 'condensed' },
  { name: 'Anton', family: "'Anton', sans-serif", category: 'condensed' },
  { name: 'Asap Condensed', family: "'Asap Condensed', sans-serif", category: 'condensed' },
  { name: 'BenchNine', family: "'BenchNine', sans-serif", category: 'condensed' },
  { name: 'Changa', family: "'Changa', sans-serif", category: 'condensed' },
  { name: 'Economica', family: "'Economica', sans-serif", category: 'condensed' },
  { name: 'League Gothic', family: "'League Gothic', sans-serif", category: 'condensed' },
  { name: 'Mallanna', family: "'Mallanna', sans-serif", category: 'condensed' },

  // =====================================================
  // SLAB - Strong and blocky (25+ fonts)
  // =====================================================
  { name: 'Alfa Slab One', family: "'Alfa Slab One', serif", category: 'slab' },
  { name: 'Arvo', family: "'Arvo', serif", category: 'slab' },
  { name: 'Bitter', family: "'Bitter', serif", category: 'slab' },
  { name: 'Bree Serif', family: "'Bree Serif', serif", category: 'slab' },
  { name: 'Crete Round', family: "'Crete Round', serif", category: 'slab' },
  { name: 'Josefin Slab', family: "'Josefin Slab', serif", category: 'slab' },
  { name: 'Patua One', family: "'Patua One', serif", category: 'slab' },
  { name: 'Roboto Slab', family: "'Roboto Slab', serif", category: 'slab' },
  { name: 'Rokkitt', family: "'Rokkitt', serif", category: 'slab' },
  { name: 'Sanchez', family: "'Sanchez', serif", category: 'slab' },
  { name: 'Slabo 13px', family: "'Slabo 13px', serif", category: 'slab' },
  { name: 'Slabo 27px', family: "'Slabo 27px', serif", category: 'slab' },
  { name: 'Zilla Slab', family: "'Zilla Slab', serif", category: 'slab' },
  { name: 'Aleo', family: "'Aleo', serif", category: 'slab' },
  { name: 'Andada Pro', family: "'Andada Pro', serif", category: 'slab' },
  { name: 'Arbutus Slab', family: "'Arbutus Slab', serif", category: 'slab' },
  { name: 'BioRhyme', family: "'BioRhyme', serif", category: 'slab' },
  { name: 'Coustard', family: "'Coustard', serif", category: 'slab' },
  { name: 'Enriqueta', family: "'Enriqueta', serif", category: 'slab' },
  { name: 'Kameron', family: "'Kameron', serif", category: 'slab' },
  { name: 'Kreon', family: "'Kreon', serif", category: 'slab' },
  { name: 'Museo Slab', family: "'Museo Slab', serif", category: 'slab' },
  { name: 'Podkova', family: "'Podkova', serif", category: 'slab' },
  { name: 'Port Lligat Slab', family: "'Port Lligat Slab', serif", category: 'slab' },
  { name: 'Rockwell', family: "'Rockwell', serif", category: 'slab' },

  // =====================================================
  // GEOMETRIC - Clean and mathematical (25+ fonts)
  // =====================================================
  { name: 'Poppins', family: "'Poppins', sans-serif", category: 'geometric' },
  { name: 'Montserrat', family: "'Montserrat', sans-serif", category: 'geometric' },
  { name: 'Raleway', family: "'Raleway', sans-serif", category: 'geometric' },
  { name: 'Jost', family: "'Jost', sans-serif", category: 'geometric' },
  { name: 'Josefin Sans', family: "'Josefin Sans', sans-serif", category: 'geometric' },
  { name: 'Comfortaa', family: "'Comfortaa', sans-serif", category: 'geometric' },
  { name: 'Nunito', family: "'Nunito', sans-serif", category: 'geometric' },
  { name: 'Quicksand', family: "'Quicksand', sans-serif", category: 'geometric' },
  { name: 'Varela Round', family: "'Varela Round', sans-serif", category: 'geometric' },
  { name: 'Poiret One', family: "'Poiret One', cursive", category: 'geometric' },
  { name: 'Questrial', family: "'Questrial', sans-serif", category: 'geometric' },
  { name: 'Philosopher', family: "'Philosopher', sans-serif", category: 'geometric' },
  { name: 'Didact Gothic', family: "'Didact Gothic', sans-serif", category: 'geometric' },
  { name: 'Gruppo', family: "'Gruppo', sans-serif", category: 'geometric' },
  { name: 'Julius Sans One', family: "'Julius Sans One', sans-serif", category: 'geometric' },
  { name: 'Megrim', family: "'Megrim', cursive", category: 'geometric' },
  { name: 'Nixie One', family: "'Nixie One', cursive", category: 'geometric' },
  { name: 'Orbitron', family: "'Orbitron', sans-serif", category: 'geometric' },
  { name: 'Poller One', family: "'Poller One', serif", category: 'geometric' },
  { name: 'Syncopate', family: "'Syncopate', sans-serif", category: 'geometric' },
  { name: 'Tenor Sans', family: "'Tenor Sans', sans-serif", category: 'geometric' },
  { name: 'Unica One', family: "'Unica One', sans-serif", category: 'geometric' },
  { name: 'Wire One', family: "'Wire One', sans-serif", category: 'geometric' },
  { name: 'Yaldevi', family: "'Yaldevi', sans-serif", category: 'geometric' },
];

// Default high-impact fonts for best results
export const DEFAULT_IMPACT_FONTS = [
  'Bangers', 'Bungee', 'Rubik Glitch', 'Rubik Spray Paint', 'Nosifer',
  'Anton', 'Creepster', 'Press Start 2P', 'Monoton', 'Fascinate',
  'Permanent Marker', 'Luckiest Guy', 'Butcherman', 'Honk', 'Nabla',
  'Eater', 'Pirata One', 'Knewave', 'Rubik Wet Paint', 'Silkscreen',
  'Stalinist One', 'Faster One', 'Lacquer', 'Major Mono Display', 'Modak',
  'Abril Fatface', 'Archivo Black', 'Bowlby One SC', 'Dela Gothic One',
  'Emblema One', 'Gravitas One', 'Sigmar One', 'Titan One', 'Ultra',
  'Bungee Shade', 'Rubik Moonrocks', 'Rubik Bubbles', 'Rowdies', 'Shrikhand',
  'Audiowide', 'Black Ops One', 'Orbitron', 'Oxanium', 'Turret Road',
  'Teko', 'Big Shoulders Display', 'Saira Stencil One', 'Climate Crisis'
];

export const PRESETS = {
  'maximum-chaos': {
    name: 'Maximum Chaos',
    framesPerCard: 1,
    fps: 60,
    duration: 2,
    fonts: DEFAULT_IMPACT_FONTS,
  },
  'fast-glitchy': {
    name: 'Fast Glitchy',
    framesPerCard: 1,
    fps: 30,
    duration: 2,
    fonts: ['Press Start 2P', 'Silkscreen', 'VT323', 'Rubik Glitch', 'Major Mono Display', 'Orbitron', 'Iceland', 'Nosifer', 'Monoton', 'Pixelify Sans', 'DotGothic16', 'Share Tech Mono'],
  },
  'clean-modern': {
    name: 'Clean Modern',
    framesPerCard: 3,
    fps: 30,
    duration: 3,
    fonts: ['Anton', 'Bebas Neue', 'Oswald', 'Russo One', 'Staatliches', 'Archivo Black', 'Fira Sans', 'Viga', 'Black Han Sans', 'Montserrat', 'Inter', 'DM Sans'],
  },
  'handwritten-flash': {
    name: 'Handwritten Flash',
    framesPerCard: 2,
    fps: 30,
    duration: 2.5,
    fonts: ['Permanent Marker', 'Luckiest Guy', 'Special Elite', 'Cabin Sketch', 'Gochi Hand', 'Kaushan Script', 'Pacifico', 'Lobster', 'Caveat', 'Dancing Script', 'Amatic SC', 'Architects Daughter'],
  },
  'horror-vibes': {
    name: 'Horror Vibes',
    framesPerCard: 2,
    fps: 24,
    duration: 3,
    fonts: ['Creepster', 'Nosifer', 'Butcherman', 'Eater', 'Irish Grover', 'Jolly Lodger', 'New Rocker', 'Pirata One', 'Sancreek', 'Smokum', 'Vampiro One', 'Grenze Gotisch', 'UnifrakturMaguntia'],
  },
  'cinematic-pop': {
    name: 'Cinematic Pop',
    framesPerCard: 4,
    fps: 24,
    duration: 3,
    fonts: ['Cinzel', 'Playfair Display', 'Graduate', 'Ultra', 'Abril Fatface', 'Cinzel Decorative', 'Diplomata SC', 'Cormorant', 'EB Garamond', 'Young Serif'],
  },
  'tiktok-punch': {
    name: 'TikTok Punch',
    framesPerCard: 1,
    fps: 60,
    duration: 1.5,
    fonts: ['Bungee', 'Lilita One', 'Righteous', 'Fugaz One', 'Fascinate', 'Bangers', 'Chewy', 'Knewave', 'Rowdies', 'Modak', 'Fredoka', 'Concert One'],
  },
  'street-graffiti': {
    name: 'Street Graffiti',
    framesPerCard: 1,
    fps: 30,
    duration: 2,
    fonts: ['Rubik Spray Paint', 'Rubik Marker Hatch', 'Rubik Wet Paint', 'Rubik Vinyl', 'Bangers', 'Kranky', 'Slackey', 'Knewave', 'Gloria Hallelujah', 'Rock Salt', 'Shadows Into Light'],
  },
  'retro-gaming': {
    name: 'Retro Gaming',
    framesPerCard: 2,
    fps: 30,
    duration: 2,
    fonts: ['Press Start 2P', 'Silkscreen', 'VT323', 'Orbitron', 'Major Mono Display', 'Iceland', 'Wallpoet', 'Gugi', 'Pixelify Sans', 'DotGothic16', 'Kode Mono'],
  },
  'elegant-luxury': {
    name: 'Elegant Luxury',
    framesPerCard: 3,
    fps: 24,
    duration: 3,
    fonts: ['Corinthia', 'Great Vibes', 'Tangerine', 'Alex Brush', 'Allura', 'Parisienne', 'Sacramento', 'Satisfy', 'Italiana', 'Cinzel Decorative'],
  },
  'futuristic-tech': {
    name: 'Futuristic Tech',
    framesPerCard: 2,
    fps: 30,
    duration: 2,
    fonts: ['Orbitron', 'Oxanium', 'Rajdhani', 'Chakra Petch', 'Electrolize', 'Michroma', 'Turret Road', 'Bruno Ace', 'Tomorrow', 'Audiowide', 'Share Tech'],
  },
  'vintage-classic': {
    name: 'Vintage Classic',
    framesPerCard: 3,
    fps: 24,
    duration: 3,
    fonts: ['Special Elite', 'Arbutus Slab', 'BioRhyme', 'Coustard', 'Goudy Bookletter 1911', 'Lora', 'Newsreader', 'Quintessential', 'Forum', 'Glass Antiqua'],
  },
  'brush-artistic': {
    name: 'Brush Artistic',
    framesPerCard: 2,
    fps: 24,
    duration: 2.5,
    fonts: ['Arizonia', 'Ballet', 'Birthstone', 'Bonheur Royale', 'Courgette', 'Great Vibes', 'Gwendolyn', 'Licorice', 'Lovers Quarrel', 'Moon Dance'],
  },
};

export type PresetKey = keyof typeof PRESETS;

// Seeded random number generator
export function seededRandom(seed: number) {
  return function() {
    seed = (seed * 9301 + 49297) % 233280;
    return seed / 233280;
  };
}

export function shuffleFonts(fonts: string[], seed: number, count: number): string[] {
  const random = seededRandom(seed);
  const result: string[] = [];
  
  for (let i = 0; i < count; i++) {
    const index = Math.floor(random() * fonts.length);
    result.push(fonts[index]);
  }
  
  return result;
}
